@echo off
SETLOCAL EnableDelayedExpansion

:: --- CONFIGURATION ---
SET "APP_NAME=WemoOps"
SET "SERVICE_EXE_NAME=wemo_service"
SET "MAIN_SCRIPT=wemo_ops_universal.py"
SET "SERVICE_SCRIPT=wemo_service_universal.py"
SET "PYTHON_CMD=python"

:: --- IMAGE PATHS ---
SET "ICON_FILE=images\app_icon.ico"
SET "WIZARD_LARGE=images\wizard_Large.bmp"
SET "WIZARD_SMALL=images\wizard_small.bmp"

echo ========================================================
echo       WEMO OPS - MASTER BUILDER (WINDOWS)
echo       Version: 4.1.0 (Warning Free)
echo ========================================================

:: 1. CHECK PYTHON
%PYTHON_CMD% --version >nul 2>&1
IF %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Python is not installed or not in your PATH.
    pause
    exit /b 1
)

:: 2. SETUP VIRTUAL ENVIRONMENT
echo [1/5] Setting up Build Environment...
if exist ".venv" (
    echo    - Cleaning old environment...
    rmdir /s /q .venv
)
%PYTHON_CMD% -m venv .venv

:: 3. INSTALL DEPENDENCIES
echo [2/5] Installing Libraries...
call .venv\Scripts\activate.bat
:: Use python -m to avoid Windows file locking errors
python -m pip install --upgrade pip
pip install "pywemo>=2.1.1" customtkinter requests pyinstaller pyperclip pystray Pillow

:: 4. BUILD EXECUTABLES
echo [3/5] Compiling Binaries...

if exist "build" rmdir /s /q build
if exist "dist" rmdir /s /q dist

:: Check for Icon
SET "ICON_FLAG="
SET "ADD_DATA_FLAG="
if exist "%ICON_FILE%" (
    echo    - Found Custom Icon: %ICON_FILE%
    SET "ICON_FLAG=--icon=%ICON_FILE%"
    SET "ADD_DATA_FLAG=--add-data %ICON_FILE%;."
) else (
    echo    - WARNING: '%ICON_FILE%' not found. Using default icon.
)

:: Build GUI App
echo    - Compiling GUI (%MAIN_SCRIPT%)...
pyinstaller --noconfirm --noconsole --onefile ^
    --name "%APP_NAME%" ^
    %ICON_FLAG% ^
    %ADD_DATA_FLAG% ^
    --collect-all customtkinter ^
    --hidden-import pywemo ^
    --hidden-import pyperclip ^
    "%MAIN_SCRIPT%"

:: Build Service
echo    - Compiling Service (%SERVICE_SCRIPT%)...
pyinstaller --noconfirm --noconsole --onefile ^
    --name "%SERVICE_EXE_NAME%" ^
    %ICON_FLAG% ^
    --hidden-import pywemo ^
    "%SERVICE_SCRIPT%"

:: 5. GENERATE INNO SETUP SCRIPT
echo [4/5] Generating Installer Config (ISS)...

SET "ISS_FILE=WemoOps.iss"
(
echo ; Script generated by WemoOps Builder
echo [Setup]
echo AppId={{A3D8C8F1-2B8E-4A9A-9C7D-1E6F5G4H3I2J}
echo AppName=%APP_NAME%
echo AppVersion=4.1.0
echo AppPublisher=Wemo Ops Project
echo DefaultDirName={userappdata}\WemoOps
echo DisableDirPage=yes
echo DisableProgramGroupPage=yes
echo OutputDir=dist
echo OutputBaseFilename=WemoOps_Setup_v4.1.0
echo Compression=lzma
echo SolidCompression=yes
echo PrivilegesRequired=lowest
echo CloseApplications=force
echo.
echo ; --- BRANDING IMAGES ---
echo SetupIconFile=%ICON_FILE%
echo WizardImageFile=%WIZARD_LARGE%
echo WizardSmallImageFile=%WIZARD_SMALL%
echo UninstallDisplayIcon={app}\%APP_NAME%.exe
echo.
echo [Languages]
echo Name: "english"; MessagesFile: "compiler:Default.isl"
echo.
echo [Tasks]
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
echo Name: "startup"; Description: "Automatically start background service"; GroupDescription: "Automation:"; Flags: checkablealone
echo.
echo [Files]
echo Source: "dist\%APP_NAME%.exe"; DestDir: "{app}"; Flags: ignoreversion
echo Source: "dist\%SERVICE_EXE_NAME%.exe"; DestDir: "{app}"; Flags: ignoreversion
echo Source: "%ICON_FILE%"; DestDir: "{app}"; DestName: "app_icon.ico"; Flags: ignoreversion
echo.
echo [Icons]
echo Name: "{userprograms}\%APP_NAME%"; Filename: "{app}\%APP_NAME%.exe"; IconFilename: "{app}\app_icon.ico"
echo Name: "{userdesktop}\%APP_NAME%"; Filename: "{app}\%APP_NAME%.exe"; IconFilename: "{app}\app_icon.ico"; Tasks: desktopicon
echo Name: "{userstartup}\WemoOps Service"; Filename: "{app}\%SERVICE_EXE_NAME%.exe"; IconFilename: "{app}\app_icon.ico"; Tasks: startup
echo.
echo [Run]
echo Filename: "{app}\%SERVICE_EXE_NAME%.exe"; Description: "Start Background Service"; Flags: nowait postinstall runasoriginaluser
echo Filename: "{app}\%APP_NAME%.exe"; Description: "Launch Dashboard"; Flags: nowait postinstall skipifsilent
echo.
echo [UninstallRun]
echo ; FIX: Added RunOnceId to silence warnings
echo Filename: "taskkill"; Parameters: "/IM %APP_NAME%.exe /F"; Flags: runhidden; RunOnceId: "KillApp"
echo Filename: "taskkill"; Parameters: "/IM %SERVICE_EXE_NAME%.exe /F"; Flags: runhidden; RunOnceId: "KillService"
echo.
echo [Code]
echo function InitializeSetup: Boolean;
echo var
echo   ResultCode: Integer;
echo begin
echo   // Kill old processes to prevent file lock errors
echo   Exec^('taskkill', '/F /IM %SERVICE_EXE_NAME%.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode^);
echo   Exec^('taskkill', '/F /IM %APP_NAME%.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode^);
echo   Result := True;
echo end;
) > "%ISS_FILE%"

:: 6. COMPILE INNO SETUP INSTALLER
echo [5/5] Compiling Installer Package...

SET "ISCC=%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe"
if not exist "%ISCC%" (
    echo.
    echo [WARNING] Inno Setup Compiler not found.
    echo Please install Inno Setup 6.
    pause
    exit /b 0
)

"%ISCC%" "%ISS_FILE%"

echo.
echo ========================================================
echo    BUILD COMPLETE!
echo    Installer: dist\WemoOps_Setup_v4.1.0.exe
echo ========================================================
pause