@echo off
SETLOCAL EnableDelayedExpansion
TITLE Wemo Ops Center - Master Build System
COLOR 0A

:: --- CONFIGURATION ---
SET "APP_NAME=WemoOps"
SET "SERVICE_EXE_NAME=wemo_service"
SET "HOOBS_EXE_NAME=Wemo_HOOBS_Integration_Setup"
SET "MAIN_SCRIPT=wemo_ops_universal.py"
SET "SERVICE_SCRIPT=wemo_server.py"
SET "HOOBS_SCRIPT=hoobs_installer.py"
SET "PYTHON_CMD=python"

:: --- IMAGE PATHS ---
SET "ICON_FILE=images\app_icon.ico"
SET "WIZARD_LARGE=images\wizard_Large.bmp"
SET "WIZARD_SMALL=images\wizard_small.bmp"

echo ========================================================
echo       WEMO OPS CENTER - MASTER BUILD SYSTEM
echo       Version: 5.3.0 (Stable UI Update)
echo ========================================================

:: 1. CHECK PYTHON
%PYTHON_CMD% --version >nul 2>&1
IF %ERRORLEVEL% NEQ 0 (
    COLOR 0C
    echo [ERROR] Python is not installed or not in your PATH.
    pause
    exit /b 1
)

:: 2. SETUP BUILD ENVIRONMENT
echo.
echo [1/7] Setting up Virtual Environment...
if exist ".venv" (
    echo    - Cleaning old environment...
    rmdir /s /q .venv
)
%PYTHON_CMD% -m venv .venv
call .venv\Scripts\activate.bat

:: 3. INSTALL DEPENDENCIES
echo.
echo [2/7] Installing Libraries...
python -m pip install --upgrade pip
pip install "pywemo>=2.1.1" customtkinter requests pyinstaller pyperclip pystray Pillow flask qrcode waitress

:: 4. VERIFY FOLDER STRUCTURE
echo.
echo [3/7] Verifying Web Assets...
if not exist "templates\index.html" (
    COLOR 0C
    echo [ERROR] templates\index.html is missing!
    echo Please ensure the 'templates' folder exists and contains index.html.
    pause
    exit /b
)
echo    - Structure confirmed.

:: 5. CLEANUP
echo.
echo [4/7] Cleaning Previous Builds...
if exist "build" rmdir /s /q build
if exist "dist" rmdir /s /q dist
if exist "WemoOps.iss" del /f /q "WemoOps.iss"

:: 6. COMPILE EXECUTABLES
echo.
echo [5/7] Compiling Binaries...

:: --- A. Build HOOBS Installer ---
echo    > Compiling HOOBS Integration Setup...
pyinstaller --noconfirm --onefile --console --clean --uac-admin ^
    --name "%HOOBS_EXE_NAME%" ^
    "%HOOBS_SCRIPT%"

IF NOT EXIST "dist\%HOOBS_EXE_NAME%.exe" (
    COLOR 0C
    echo [!] CRITICAL: %HOOBS_EXE_NAME%.exe failed to build.
    pause
    exit /b
)

:: --- B. Build Main Dashboard ---
echo    > Compiling Main Dashboard (%APP_NAME%)...
SET "ICON_FLAG="
SET "ADD_DATA_FLAG="
if exist "%ICON_FILE%" (
    SET "ICON_FLAG=--icon=%ICON_FILE%"
    SET "ADD_DATA_FLAG=--add-data %ICON_FILE%;images"
)

pyinstaller --noconfirm --noconsole --onefile ^
    --name "%APP_NAME%" ^
    %ICON_FLAG% ^
    %ADD_DATA_FLAG% ^
    --collect-all customtkinter ^
    --hidden-import pywemo ^
    --hidden-import pyperclip ^
    --hidden-import qrcode ^
    --hidden-import PIL ^
    "%MAIN_SCRIPT%"

IF NOT EXIST "dist\%APP_NAME%.exe" (
    COLOR 0C
    echo [!] CRITICAL: %APP_NAME%.exe failed to build. Check Python syntax.
    pause
    exit /b
)

:: --- C. Build Background Service ---
echo    > Compiling Background Service (%SERVICE_EXE_NAME%)...
:: Note: We explicitly add the templates and static folders here
pyinstaller --noconfirm --noconsole --onefile ^
    --name "%SERVICE_EXE_NAME%" ^
    %ICON_FLAG% ^
    --add-data "templates;templates" ^
    --add-data "static;static" ^
    --hidden-import pywemo ^
    --hidden-import flask ^
    --hidden-import waitress ^
    "%SERVICE_SCRIPT%"

IF NOT EXIST "dist\%SERVICE_EXE_NAME%.exe" (
    COLOR 0C
    echo [!] CRITICAL: %SERVICE_EXE_NAME%.exe failed to build.
    pause
    exit /b
)

:: 7. GENERATE INNO SETUP SCRIPT
echo.
echo [6/7] Generating Installer Config (ISS)...

SET "ISS_FILE=WemoOps.iss"
(
echo ; Script generated by WemoOps Master Builder
echo [Setup]
echo AppId={{A3D8C8F1-2B8E-4A9A-9C7D-1E6F5G4H3I2J}
echo AppName=%APP_NAME%
echo AppVersion=5.3.0
echo AppPublisher=Wemo Ops Project
echo DefaultDirName={userappdata}\WemoOps
echo DisableDirPage=yes
echo DisableProgramGroupPage=yes
echo Uninstallable=yes
echo OutputDir=dist
echo OutputBaseFilename=WemoOps_Setup_v5.3.0
echo Compression=lzma
echo SolidCompression=yes
echo PrivilegesRequired=lowest
echo CloseApplications=force
echo.
echo ; --- BRANDING ---
if exist "%ICON_FILE%" echo SetupIconFile=%ICON_FILE%
if exist "%WIZARD_LARGE%" echo WizardImageFile=%WIZARD_LARGE%
if exist "%WIZARD_SMALL%" echo WizardSmallImageFile=%WIZARD_SMALL%
echo UninstallDisplayIcon={app}\%APP_NAME%.exe
echo.
echo [Languages]
echo Name: "english"; MessagesFile: "compiler:Default.isl"
echo.
echo [Tasks]
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
echo Name: "startup"; Description: "Automatically start background service"; GroupDescription: "Automation:"; Flags: checkablealone
echo.
echo [Files]
echo ; 1. Main Dashboard
echo Source: "dist\%APP_NAME%.exe"; DestDir: "{app}"; Flags: ignoreversion
echo ; 2. Background Service
echo Source: "dist\%SERVICE_EXE_NAME%.exe"; DestDir: "{app}"; Flags: ignoreversion
echo ; 3. HOOBS Integration Installer
echo Source: "dist\%HOOBS_EXE_NAME%.exe"; DestDir: "{app}"; Flags: ignoreversion
echo ; 4. Assets
if exist "%ICON_FILE%" echo Source: "%ICON_FILE%"; DestDir: "{app}"; DestName: "app_icon.ico"; Flags: ignoreversion
echo.
echo [Icons]
echo Name: "{userprograms}\%APP_NAME%"; Filename: "{app}\%APP_NAME%.exe"; IconFilename: "{app}\app_icon.ico"
echo Name: "{userdesktop}\%APP_NAME%"; Filename: "{app}\%APP_NAME%.exe"; IconFilename: "{app}\app_icon.ico"; Tasks: desktopicon
echo Name: "{userstartup}\WemoOps Service"; Filename: "{app}\%SERVICE_EXE_NAME%.exe"; IconFilename: "{app}\app_icon.ico"; Tasks: startup
echo.
echo [Run]
echo Filename: "{app}\%SERVICE_EXE_NAME%.exe"; Description: "Start Background Service"; Flags: nowait postinstall runasoriginaluser
echo Filename: "{app}\%APP_NAME%.exe"; Description: "Launch Dashboard"; Flags: nowait postinstall skipifsilent
echo.
echo [UninstallRun]
echo Filename: "taskkill"; Parameters: "/IM %APP_NAME%.exe /F"; Flags: runhidden; RunOnceId: "KillApp"
echo Filename: "taskkill"; Parameters: "/IM %SERVICE_EXE_NAME%.exe /F"; Flags: runhidden; RunOnceId: "KillService"
echo.
echo [Code]
echo function InitializeSetup: Boolean;
echo var
echo   ResultCode: Integer;
echo begin
echo   // Kill old processes
echo   Exec^('taskkill', '/F /IM %SERVICE_EXE_NAME%.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode^);
echo   Exec^('taskkill', '/F /IM %APP_NAME%.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode^);
echo   Result := True;
echo end;
) > "%ISS_FILE%"

:: 8. COMPILE INNO SETUP INSTALLER
echo.
echo [7/7] Packaging Final Installer...

SET "ISCC=%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe"
if not exist "%ISCC%" (
    echo.
    echo [WARNING] Inno Setup Compiler not found at: "%ISCC%"
    echo Please compile "%ISS_FILE%" manually or install Inno Setup 6.
    pause
    exit /b 0
)

"%ISCC%" "%ISS_FILE%"

echo.
echo ========================================================
echo    BUILD COMPLETE!
echo    Installer is in: dist\WemoOps_Setup_v5.3.0.exe
echo ========================================================
pause